# Generated by Django 4.2.9 on 2024-03-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='language',
        ),
    ]
