# Generated by Django 4.2.9 on 2024-04-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
