"""
Django settings for myjob project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xy%*(bmv_wq3t@rp&h&rrpe1)q&thz_yorkz^dipr)1d9rzg0l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'tinymce',
    'users',
    'applicant',
    'recruiter',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myjob.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myjob.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR , 'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR , 'mediafiles')


RAZOR_KEY_ID = 'rzp_test_bkUvdizg5rUdQj'
RAZOR_KEY_SECRET = 'WbV54ypElH4ADchIRax9yAmt'


# settings.py

TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'width': 800,
    'menubar': True,
    'plugins': '''
        advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen
        insertdatetime media table contextmenu paste code help wordcount
        textpattern nonbreaking save insertdatetime contextmenu directionality
        template advlist autolink lists link image charmap print preview anchor
        searchreplace visualblocks code fullscreen
        insertdatetime media table contextmenu paste code help wordcount
        textpattern nonbreaking save insertdatetime contextmenu directionality
        template
    ''',
    'toolbar': '''
        formatselect | bold italic strikethrough forecolor backcolor
        | alignleft aligncenter alignright alignjustify
        | bullist numlist outdent indent | removeformat
        | image link | code fullscreen | media | table | paste
        | searchreplace | preview | save | insertdatetime | code
        | visualblocks | contextmenu | nonbreaking | wordcount
        | textpattern | directionality | template | advlist
        | styleselect | fontselect fontsizeselect | blockquote | subscript superscript
    ''',
    'contextmenu': 'link image inserttable | cell row column deletetable',
    'visualblocks_default_state': True,
    'paste_data_images': True,
    'image_advtab': True,
    'media_live_embeds': True,
    'insertdatetime_formats': [
        '%Y-%m-%d',    # Default format
        '%H:%M:%S',    # Time format
        '%I:%M:%S %p', # 12-hour time format with AM/PM
    ],
    'table_default_attributes': {
        'class': 'table table-bordered',  # Bootstrap table classes
    },
    'table_default_styles': {
        'border-collapse': 'collapse',  # Collapse table borders
        'width': '100%',                # Full width tables
    },
    'autosave_ask_before_unload': False,
    'autosave_interval': '30s',
    'powerpaste_allow_local_images': True,
    'spellchecker_dialog': True,
    'spellchecker_whitelist': ['Ephox', 'Moxiecode'],
    'spellchecker_rpc_url': 'https://spellchecker.tinymce.com/ephox-spelling',
    'spellchecker_languages': 'English=en,Danish=da,Dutch=nl,Finnish=fi,French=fr,German=de,Italian=it,Polish=pl,Portuguese=pt,Spanish=es,Swedish=sv',
    'code_dialog_height': 600,
    'code_dialog_width': 800,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtpout.secureserver.net'
EMAIL_PORT = 465
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'contact@theworkinglady.in'
EMAIL_HOST_PASSWORD = 'Theworkinglady@2024'