# Generated by Django 4.2.9 on 2024-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0007_remove_work_work_category_work_work_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('recruiter_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(default=False, max_length=15)),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=60)),
                ('requirement', models.CharField(default=False, max_length=60)),
                ('full_name', models.CharField(max_length=60)),
                ('provided_salary', models.CharField(blank=True, max_length=12, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('urgency', models.CharField(default=False, max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('experience', models.IntegerField(default=0)),
                ('timing', models.CharField(default=False, max_length=30)),
                ('preffered_location', models.CharField(default=False, max_length=50)),
                ('source', models.CharField(default=False, max_length=50)),
                ('job', models.ManyToManyField(to='applicant.work')),
            ],
        ),
    ]
