# Generated by Django 4.2.9 on 2024-03-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='posted_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
