# Generated by Django 4.2.9 on 2024-03-28 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicants_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruiter', '0002_recruiter_posted_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='recruiter_id',
            new_name='recruiterId',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='applicants',
            field=models.ManyToManyField(blank=True, null=True, to='applicant.applicants'),
        ),
        migrations.CreateModel(
            name='User_Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recruiter',
            name='recruiter',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='recruiter.user_recruiter'),
        ),
    ]
