# Generated by Django 4.2.9 on 2024-03-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0003_rename_recruiter_id_recruiter_recruiterid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recruiter.user_recruiter'),
        ),
    ]
