# Generated by Django 4.2.9 on 2024-03-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_alter_recruiter_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='applicants',
            new_name='selected_applicants',
        ),
    ]
