# Generated by Django 4.2.9 on 2024-04-03 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_alter_recruiter_recruiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruiter.user_recruiter'),
        ),
    ]
