# Generated by Django 5.0.4 on 2024-04-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0011_alter_recruiter_recruiterid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_for', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=15)),
                ('pack', models.CharField(max_length=30)),
                ('maid_type', models.CharField(max_length=50)),
                ('working_hours', models.CharField(max_length=50)),
                ('support', models.CharField(max_length=20)),
            ],
        ),
    ]
