# Generated by Django 4.2.9 on 2024-04-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0012_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='pin_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=30),
        ),
    ]
