# Generated by Django 4.2.9 on 2024-04-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_recruiter_pin_code_alter_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_recruiter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
    ]
