# Generated by Django 4.2.9 on 2024-03-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicants_expected_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='job_time',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='skills',
        ),
        migrations.AddField(
            model_name='applicants',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='job_duration',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='applicants',
            name='last_salary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicants',
            name='phone_number2',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.AddField(
            model_name='applicants',
            name='preffered_location',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='applicants',
            name='qualification',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='applicants',
            name='religion',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='phone_number',
            field=models.CharField(default=False, max_length=15),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('Work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(max_length=50)),
                ('work_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.work_category')),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='job',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='applicant.work'),
        ),
        migrations.AddField(
            model_name='applicants',
            name='work_place',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='applicant.work_category'),
        ),
    ]
