# Generated by Django 4.2.9 on 2024-03-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_alter_applicants_experience_remove_applicants_job_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_category',
        ),
        migrations.AddField(
            model_name='work',
            name='work_category',
            field=models.ManyToManyField(to='applicant.work_category'),
        ),
    ]
