# Generated by Django 4.2.9 on 2024-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_alter_applicants_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='applicant_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
